name: Scraper Pre칞os (Hortol칙ndia & Campinas)

on:
  schedule:
    - cron: '0 0 * * *'     # Roda automaticamente todo dia  meia-noite
  workflow_dispatch:        # Permite rodar manualmente clicando no bot칚o

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      # --- BLOCO 1: HORTOL츽NDIA ---
      #- name: 游 Executar Scrapers Hortol칙ndia
        #run: |
          #echo "Iniciando captura de Hortol칙ndia..."
          #node scrapers/hortolandia/scraper_tenda.js
          #node scrapers/hortolandia/scraper_goodbom.js
          #node scrapers/hortolandia/scraper_arena.js
          #node scrapers/hortolandia/scraper_savegnago.js
          #node scrapers/hortolandia/hortolandia_compare.js

      # --- BLOCO 2: CAMPINAS ---
      - name: 游끽 Executar Scrapers Campinas
        run: |
          echo "Iniciando captura de Campinas..."
          #node scrapers/campinas/scraper_carrefour.js
          node scrapers/campinas/scraper_giga.js
          #node scrapers/campinas/scraper_covabra.js
          #node scrapers/campinas/scraper_paguemenos.js
          #node scrapers/campinas/scraper_atacadao.js
          #node scrapers/campinas/scraper_enxuto.js
          #node scrapers/campinas/scraper_tenda.js
          node scrapers/campinas/campinas_compare.js

      # --- SALVAR RESULTADOS ---
      - name: 游 Commit and push updated prices
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@users.noreply.github.com"
          git add docs/prices/*.json
          # O '|| true' evita que o Action falhe se n칚o houver mudan칞a nos pre칞os
          git commit -m "Pre칞os atualizados: Hortol칙ndia e Campinas [skip ci]" || true
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
